typography_spectrum: 0.37660289532504976
color:
  brandStrength: 0.8399108205921948
  lightness: 0.7389174005948007
  saturation: 0.7217579418793321
  rhythmicContrast: 0.463625029893592
  brandColors:
    - '#FFFFFF'
    - '#003060'
    - '#B3BFCC'
    - '#869DB4'
    - '#476A8A'
layout_spectrum: 0.797815247438848
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6933a5fd-6614-4cf5-8ff7-07b9168b3042.jpg
name: Coveca Consulting
navigation:
  - name: Resources
    url: 'http://mindtools.com'
    type: external
  - name: About Us
    url: 'https://ch.linkedin.com/in/marcdimancescu'
    type: external
title: Strategic Marketing & Implementation
